blender_fund/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

from blender_fund_main.views import errors

handler500 = errors.error_handler_500


urlpatterns = (
    [
        path('accounts/', include('allauth.urls')),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', include('loginas.urls')),
        path('admin/notes/', include('blender_notes.urls')),
        path('admin/', admin.site.urls),
        path('error/500', errors.test_error_500),
        path('', include('blender_fund_main.urls')),
        path('', include('looper.urls')),
        # Flatpages
        path('about/', views.flatpage, {'url': '/about/'}, name='flatpage-about'),
        path('grants/', views.flatpage, {'url': '/grants/'}, name='flatpage-grants'),
        path('contact/', views.flatpage, {'url': '/contact/'}, name='flatpage-contact'),
        path(
            'corporate-memberships/',
            views.flatpage,
            {'url': '/corporate-memberships/'},
            name='flatpage-corporate-memberships',
        ),
        path('donate-once/', views.flatpage, {'url': '/donate-once/'}, name='flatpage-donate-once'),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blender_fund_main/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from looper.views import settings as looper_settings
import looper.views.checkout_stripe as checkout_stripe

from .views import (
    activity,
    development,
    errors,
    express_checkout,
    landing,
    link_membership_or_donation,
    settings,
    survey,
    webhooks,
)

urlpatterns = [
    path('', landing.landing, name='landing'),
    path('campaign/', landing.landing_campaign, name='landing_campaign'),
    path('campaign/orders_raw', landing.get_orders_json_raw, name='orders_json_campaign_raw'),
    path('thanks/', RedirectView.as_view(url=reverse_lazy('landing'))),
    # The settings/ path prefix is shared between this module and looper.urls.
    path('settings/', settings.settings_home, name='settings_home'),
    path('settings/receipts/', looper_settings.settings_receipts, name='settings_receipts'),
    path(
        'settings/receipts/<int:order_id>',
        looper_settings.ReceiptView.as_view(),
        name='settings_receipt',
    ),
    path(
        'settings/receipts/blender-fund-<int:order_id>.pdf',
        looper_settings.ReceiptPDFView.as_view(),
        name='settings_receipt_pdf',
    ),
    path('settings/membership/', RedirectView.as_view(
        url=reverse_lazy('settings_home'),
        permanent=False)),
    path('settings/membership/<int:membership_id>', settings.MembershipView.as_view(),
         name='settings_membership_edit'),
    path('settings/membership/<int:membership_id>/cancel', settings.CancelMembershipView.as_view(),
         name='settings_membership_cancel'),
    path('settings/membership/cancelviatoken/<token>',
         settings.CancelMembershipViaTokenView.as_view(),
         name='settings_membership_cancel_via_token'),

    path(
        'settings/billing/payment-methods/change/<int:subscription_id>',
        looper_settings.PaymentMethodChangeView.as_view(
            success_url='payment_method_change_done',
            cancel_url='settings_home',
        ),
        name='payment_method_change',
    ),
    path(
        'settings/billing/payment-methods/change-done/<int:subscription_id>/<stripe_session_id>',
        # TODO? settings_home redirects to settings_membership_edit if there is just one membership
        # so this is good for 99%
        # as an improvement we could make success_url parameter a callable that does a proper
        # pk lookup and explicitly redirects to settings_membership_edit
        looper_settings.PaymentMethodChangeDoneView.as_view(success_url='settings_home'),
        name='payment_method_change_done',
    ),

    path(
        'checkout/pay/<int:order_id>',
        checkout_stripe.CheckoutExistingOrderView.as_view(cancel_url='settings_home'),
        name='checkout_existing_order',
    ),

    # Flexible payment
    path('settings/membership/<int:membership_id>/extend', settings.ExtendMembershipView.as_view(),
         name='membership_extend'),
    path('settings/membership/<int:membership_id>/extend-done/<stripe_session_id>',
         settings.ExtendMembershipDoneView.as_view(),
         name='membership_extend_done'),
    path('settings/membership/<int:membership_id>/extend-not-possible',
         settings.ExtendMembershipNotPossibleView.as_view(),
         name='membership_extend_not_possible'),

    path('my-permissions', development.my_permissions),
    path('test-error/500', errors.test_error_500),
    path('activity/', activity.ActivityListView.as_view(), name='activity-list'),
    path('activity/reports/', activity.ReportsView.as_view(), name='activity-reports'),
    path(
        'link-membership/<token>/',
        link_membership_or_donation.LinkMembershipView.as_view(),
        name='link_membership',
    ),
    path(
        'link-donation/<token>/',
        link_membership_or_donation.LinkDonationView.as_view(),
        name='link_donation',
    ),
    path(
        'express-checkout/',
        express_checkout.ExpressCheckoutDonateOnceView.as_view(),
        name='express_checkout_donate_once',
    ),
    path(
        'express-checkout/<int:plan_variation>/',
        express_checkout.ExpressCheckoutPlanVariationView.as_view(),
        name='express_checkout_plan_variation',
    ),
    path(
        'donate-once-thank-you/',
        express_checkout.DonateOnceThankYou.as_view(),
        name='donate_once_thank_you'
    ),
    path(
        'donate-once-thank-you/display-name/',
        express_checkout.save_donation_display_name,
        name='save_donation_display_name',
    ),
    path(
        'stripe-success-create-subscription/<stripe_session_id>',
        checkout_stripe.StripeSuccessCreateSubscriptionView.as_view(),
        name='stripe_success_create_subscription',
    ),
    path('webhooks/stripe/', webhooks.StripeWebhookView.as_view(), name='webhook_stripe'),
    path(
        'survey/',
        survey.SurveyView.as_view(),
        name='survey'
    ),
    path(
        'survey/done/',
        survey.SurveyDoneView.as_view(),
        name='survey-done'
    ),
]

blender_fund_main/models.py
import logging
import typing

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

import looper.model_mixins
import looper.exceptions
from looper.models import Subscription, Plan
from looper.money import Money

log = logging.getLogger(__name__)


class MembershipLevel(looper.model_mixins.RecordModificationMixin, models.Model):
    # There seems to be no integrated way to create a multiselect with arbirary values, so we store
    # them here in a list.
    # TODO validate visible_attributes on save agains the list and provide helpful error message
    # TODO(Sybren): ensure that this list always matches properties of the Membership and
    # MembershipForm classes.
    ALLOWED_VISIBLE_ATTRIBUTES = ['display_name', 'description', 'url', 'logo']

    CATEGORIES = [
        ('INDIV', 'Individual'),
        ('CORP', 'Corporate'),
    ]

    record_modification_fields = {'bid_badge_name', 'is_visible'}

    category = models.CharField(max_length=6, choices=CATEGORIES)
    name = models.CharField(max_length=250)
    # Visible attributes are properties of the Membership model (name, description, url, logo)
    visible_attributes = models.CharField(
        max_length=250, null=False, blank=True, default='',
        help_text=f'Comma separated attributes. Spaces will be stripped. '
                  f'Choose from {", ".join(ALLOWED_VISIBLE_ATTRIBUTES)}')
    is_visible = models.BooleanField(
        editable=False, default=False,
        help_text='Whether memberships of this level have any visible attributes.')
    details_html = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='membershiplevels/', null=True, blank=True,
        help_text='Image shown on the front page')
    bid_badge_name = models.CharField(
        max_length=80, null=False, default='', blank=True,
        help_text='Blender ID badge associated with this membership level. Note that Blender ID '
                  'must be set up to allow management of this badge. Also note that changing this '
                  'badge name does not adjust the badges of already-existing membership holders.')
    # Optionally sort membership levels (used in landing page)
    order = models.PositiveIntegerField(null=True, blank=True)
    plan = models.OneToOneField(Plan, on_delete=models.CASCADE, null=True, blank=True, related_name='membership')
    is_popular = models.BooleanField(default=False,
                                     help_text='Show as "popular" on the landing page.')

    class Meta:
        ordering = ['order', 'name']

    @property
    def visible_attributes_set(self) -> typing.Set[str]:
        if not self.visible_attributes:
            return set()
        return set(self._visible_attributes)

    @property
    def visible_attributes_list(self) -> typing.List[str]:
        if not self.visible_attributes:
            return []
        return list(self._visible_attributes)

    @property
    def _visible_attributes(self) -> typing.Iterable[str]:
        if not self.visible_attributes:
            return ()
        return (attr.strip() for attr in self.visible_attributes.split(','))

    @property
    def hidden_attributes_set(self) -> typing.Set[str]:
        """In some cases we want to hide form fields."""
        return set(self.ALLOWED_VISIBLE_ATTRIBUTES) - self.visible_attributes_set

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs) -> None:
        is_new: bool = not self.pk
        self.is_visible = bool(self.visible_attributes)

        was_changed, old_state = self.pre_save_record(*args, **kwargs)

        if was_changed and old_state.get('is_visible') != self.is_visible:
            update_fields = kwargs.get('update_fields')
            if update_fields is not None:
                update_fields.add('is_visible')

        super().save(*args, **kwargs)

        if not was_changed or is_new:
            return
        self._refresh_bid_badges(old_state)

    def _refresh_bid_badges(self, old_state: looper.model_mixins.OldStateType) -> None:
        """Detect a change in BID badge name, and reassign badges."""

        old_bid_badge_name: str = old_state.get('bid_badge_name', '')
        if old_bid_badge_name == self.bid_badge_name:
            return

        log.info('MembershipLevel %r pk=%d change BID badge name from %r to %r, '
                 'updating memberships', self.name, self.pk, old_bid_badge_name,
                 self.bid_badge_name)
        for membership in self.membership_set.exclude(granted_badge=self.bid_badge_name):
            # Just save the membership, it's enough to trigger the post-save
            # signal that refreshes the badges.
            membership.save()

    def price_per_month(self, currency: str) -> typing.Optional[Money]:
        """Compute the price per month for this membership level.

        It is assumed that all payment plan variations for this level
        represent the same amount of money per unit of time, so a random
        one of the correct currency is chosen.

        Note that this is a lossy operation, as it rounds down to entire cents.

        :return: the price per month, or None if there is no payment plan
            variation for the requested currency.
        """
        planvar = self.plan.variation_for_currency(currency)
        if planvar is None:
            return None
        return planvar.price_per_month


class MembershipManager(models.Manager):

    def active(self) -> models.QuerySet:
        """Return QuerySet of only the active memberships."""
        return self.filter(status='active')

    def visible(self) -> models.QuerySet:
        """Return QuerySet of only the publicly visible memberships."""
        return self.active().filter(level__is_visible=True, is_private=False)


# Ignoring type because of the inner Meta class of the two mix-ins.
class Membership(looper.model_mixins.RecordModificationMixin,  # type: ignore
                 looper.model_mixins.CreatedUpdatedMixin,
                 models.Model):
    """A Development Fund Membership.

    Membership can be managed manually, or in relation to a Subscription. Depending
    on the membership level, users can edit different sets of attributes. In the
    current implementation:

    - Main:      Name, URL, Logo, Description
    - Diamond:   Name, URL, Logo
    - Titanium:  Name, URL
    - Platinum:  Name, URL
    - Gold:      Name

    """
    record_modification_fields = {'status', 'granted_badge', 'customer', 'customer_id'}
    log = log.getChild('Membership')

    STATUS_DEFAULT = 'inactive'
    STATUSES = (
        'active',
        # Note that the 'inactive' state may require inspection of the subscription,
        # as 'inactive' can mean:
        #   - 'waiting for payment' (subscription status 'on-hold'), or
        #   - 'cancelled' (subscription status 'cancelled').
        'inactive',
    )
    STATUS_CHOICES = tuple((status, status.title()) for status in STATUSES)

    customer = models.ForeignKey('looper.Customer', on_delete=models.CASCADE, related_name='memberships')
    subscription = models.OneToOneField(Subscription, on_delete=models.SET_NULL,
                                        null=True, blank=True)
    display_name = models.CharField(
        max_length=255,
        null=True, blank=True,
        help_text='Name to show on the front page, if this membership is shown on the front page.')
    description = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    suppress_nofollow = models.BooleanField(
        default=False,
        help_text="Don't use rel=nofollow when rendering url in credits",
    )
    logo = models.ImageField(upload_to='logo', null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, default=STATUS_DEFAULT, max_length=20)
    is_private = models.BooleanField(default=False)  # Hide Membership to the world
    level = models.ForeignKey(MembershipLevel, on_delete=models.CASCADE)

    granted_badge = models.CharField(
        max_length=80, default='', blank=True, editable=False,
        help_text='The granted Blender ID badge for this membership, if any was granted yet.'
    )
    is_managed = models.BooleanField(
        default=False, editable=False,
        help_text="Whether this membership's subscription is a managed subscription")

    objects = MembershipManager()

    def __str__(self):
        return f"{self.level.name} - {self.display_name!r}"

    @property
    def bid_badge(self) -> str:
        """Blender ID badge that should be granted for this Membership.

        Takes the status of the membership into account.

        :return: the badge name, or an empty string if no badge should be granted.
        """
        if self.status == 'active' and not self.is_private:
            return self.level.bid_badge_name or ''
        return ''

    def save(self, *args, **kwargs) -> None:
        # Late import because 'signals' imports this module.
        from . import signals

        was_changed, old_state = self.pre_save_record(*args, **kwargs)

        super().save(*args, **kwargs)

        if not was_changed:
            return

        if old_state.get('customer_id') != self.customer_id:
            self._handle_customer_changed(old_state.get('customer_id'))

        old_status = old_state.get('status', '')
        if old_status == self.status:
            return

        self.log.info('Membership %r changed status %r to %r',
                      self.pk, old_status, self.status)
        try:
            if self.status == 'active':
                signals.membership_activated.send(sender=self, old_status=old_status)
            elif old_status == 'active':
                signals.membership_deactivated.send(sender=self, old_status=old_status)
        except Exception:

blender_fund_main/views.py
from oauth2_provider.views.generic import ProtectedResourceView
from django.contrib.auth.mixins import LoginRequiredMixin

class SomeProtectedView(LoginRequiredMixin, ProtectedResourceView):
    def get(self, request, *args, **kwargs):
        # Your view logic here
        pass

blender_fund_main/views/development.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


@login_required()
def my_permissions(request) -> JsonResponse:
    permissions = request.user.get_all_permissions()
    return JsonResponse(sorted(permissions), safe=False)

blender_fund_main/templates/blender_fund_main/components/field_label_wrapped.html
{% spaceless %}
  {% if not field.is_hidden %}
    <label for="{{ field.id_for_label }}">
      <span class="mr-3">{{ field.label }}{#% if field.field.required %}<span class="ms-1 subtitle fw-bold">*</span>{% endif %#}</span>
    </label>
  {% endif %}
  {{ field }}
  {% if field.help_text %}
    <small class="small subtitle ms-2">{{ field.help_text }}</small>
  {% endif %}
  <div class="invalid-feedback">{{ field.errors }}</div>
{% endspaceless %}

blender_fund_main/templates/blender_fund_main/components/fireworks.html
<script src="//cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.min.js"></script>
<script>
  window.human = false;

  var canvasEl = document.querySelector('.fireworks');
  var ctx = canvasEl.getContext('2d');
  var numberOfParticules = 50;
  var colors = ['#FFBA08', '#08a7FF', '#FFFFFF'];

  function setCanvasSize() {
    canvasEl.width = window.innerWidth;
    canvasEl.height = window.innerHeight;
    canvasEl.style.width = window.innerWidth + 'px';
    canvasEl.style.height = window.innerHeight + 'px';
  }

  function setParticuleDirection(p) {
    var angle = anime.random(0, 360) * Math.PI / 180;
    var value = anime.random(50, 180);
    var radius = [-1, 1][anime.random(0, 1)] * value;
    return {
      x: p.x + radius * Math.cos(angle),
      y: p.y + radius * Math.sin(angle)
    }
  }

  function createParticule(x,y) {
    var p = {};
    p.x = x;
    p.y = y;
    p.color = colors[anime.random(0, colors.length - 1)];
    p.radius = anime.random(4, 16);
    p.endPos = setParticuleDirection(p);
    p.draw = function() {
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.radius, 0, 2 * Math.PI, true);
      ctx.fillStyle = p.color;
      ctx.fill();
    }
    return p;
  }

  function renderParticule(anim) {
    for (var i = 0; i < anim.animatables.length; i++) {
      anim.animatables[i].target.draw();
    }
  }

  function animateParticules(x, y) {
    var particules = [];
    for (var i = 0; i < numberOfParticules; i++) {
      particules.push(createParticule(x, y));
    }
    anime.timeline().add({
      targets: particules,
      x: function(p) { return p.endPos.x; },
      y: function(p) { return p.endPos.y; },
      radius: 0,
      duration: anime.random(1200, 6400),
      easing: 'easeOutExpo',
      update: renderParticule
    });
  }

  var render = anime({
    duration: Infinity,
    update: function() {
      ctx.clearRect(0, 0, canvasEl.width, canvasEl.height);
    }
  });

  var centerX = canvasEl.width / 2;
  var centerY = canvasEl.height / 2;

  var centerYPadding = window.innerHeight / 4;

  function autoClick() {
    animateParticules(
      anime.random(0, window.innerWidth),
      anime.random(50, window.innerHeight / 3)
    );
    anime({duration: 1200}).finished.then(autoClick);
  }

  autoClick();
  setCanvasSize();
  window.addEventListener('resize', setCanvasSize, false);
</script>

blender_fund_main/templates/blender_fund_main/components/form.html
{% load filters %}
{% with form=form|add_form_classes %}
  {% for field in form %}
    {% include "blender_fund_main/components/field_label_wrapped.html" %}
  {% endfor %}
{% endwith %}

blender_fund_main/templates/blender_fund_main/components/form_donate_once_credit.html
<div class="row">
  <div class="col base-form-donation-display-name">
    <h2>Make it Public</h2>
    <p>
      Your gift is now part of the pile! By default it is anonymous but
      you can specify a label to make it unique.
    </p>

    <p class="mb-0">This is how your donation will appear in the
      <a href="{% url 'activity-list' %}">activity page</a>:</p>

    <div class="stats-activity mt-0 mb-2 p-0 text-center">
      <ul class="list-unstyled">
        <li class="a-cat-donation text-dark bg-light rounded py-2">
          <i class="i-activity"></i>
          <span class="x-display-name">Someone</span> donated {{ amount.with_currency_symbol_nonocents }}
        </li>
      </ul>
    </div>

    <div class="x-save-confirm text-success float-right mr-3"><b>Saved ✔</b></div>
    <form class="form" autocomplete="off">
      {% csrf_token %}
      {% include "blender_fund_main/components/form.html" %}
      <div class="x-form-errors text-danger position-absolute"></div>
      <button class="x-btn-save btn btn-primary btn-block mt-4" disabled>
        <i class="i-check"></i>
        <span>Save Public Name</span>
      </button>
    </form>
  </div>
</div>

<script>
  (function() {
    const baseEl = document.querySelector('.base-form-donation-display-name');
    function getEl(selector) {
      return baseEl.querySelector(selector);
    };
    const input = getEl('form #id_display_name');
    const preview = getEl('.x-display-name');
    const errorsEl = getEl('.x-form-errors');
    const form = getEl('form');
    const btn = getEl('.x-btn-save');
    const confirmEl = getEl('.x-save-confirm');

    input.addEventListener('input', function(e) {
      btn.disabled = false;
    }, {once: true});
    input.addEventListener('input', function(e) {
      preview.innerText = e.target.value || 'Someone';
    });

    form.addEventListener('submit', function(e) {
      e.preventDefault();
      btn.disabled = true;
      errorsEl.innerText = '';
      const data = new FormData(e.target);
      fetch('{% url "save_donation_display_name" %}', {
        method: 'POST',
        body: data,
        credentials: 'same-origin'
      }).then(function(response) {
        return response.json();
      }).then(function(data) {
        if (data && data.display_name) {
          input.value = data.display_name;
          confirmEl.classList.add('show');
        } else {
          var errorMsg = "I'm sorry Dave, I'm afraid I can't do that";
          if (data && data.errors) {
            if (data.errors.display_name && data.errors.display_name.length > 0) {
              errorMsg = data.errors.display_name[0];
            }
          }
          errorsEl.innerText = errorMsg;
        }
        setTimeout(function() {confirmEl.classList.remove('show');}, 1300);
        btn.disabled = false;
      });
      return false;
    });
  })();
</script>

blender_fund_main/templates/blender_fund_main/components/pagination.html
<ul class="pagination">
  {% if page_obj.has_previous %}
  <li class="page-item page-first">
    <a href="?page=1"><i class="i-chevron-left"></i> First</a>
  </li>
  <li class="page-item page-prev">
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
  </li>
  {% endif %}

  <li class="page-item page-current">
    <a href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
  </li>

  {% if page_obj.has_next %}
  <li class="page-item page-next">
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
  </li>
  <li class="page-item page-last">
    <a href="?page={{ page_obj.paginator.num_pages }}">Last <i class="i-chevron-right"></i> </a>
  </li>
  {% endif %}
</ul>

blender_fund_main/templates/blender_fund_main/components/set_donated_at_cookie.html
<script>
  (function() {
    const days = 90;
    // paid_at is assumed to a unix timestamp, donatedAt value is set to a unix timestamp as well
    const donatedAt = new Date(parseInt("{{ paid_at }}") * 1000);
    const expiresAt = new Date(donatedAt.getTime() + (days * 24 * 60 * 60 * 1000));
    const cookieValue = donatedAt.getTime() + "; domain=.blender.org; path=/; expires=" + expiresAt.toUTCString();
    document.cookie = "donatedAt=" + cookieValue + "; SameSite=None; Secure";
  })();
</script>

blender_fund_main/templates/blender_fund_main/components/survey_field_multi_option.html
{% load filters %}

<option value="{{ value }}" {% if value in survey.response_data|get_attr:name %}selected{% endif %} {% if translate %}translate="no"{% endif %}>
  {{ label }}
</option>

blender_fund_main/templates/blender_fund_main/components/survey_field_number.html
{% load filters %}

<div>
  {% if label %}
    <label for="{{ name }}_{{ id }}">{{ label }}</label>
  {% endif %}
  <input
    class="form-control {{ class }}"
    type="number"
    name="{{ name }}"
    id="{{ name }}_{{ id }}"
    {% if min %}min="{{ min }}"{% endif %}
    {% if max %}max="{{ max }}"{% endif %}
    {% if step %}step="{{ step }}"{% endif %}
    {% if survey.response_data|get_attr:name %}value="{{ survey.response_data|get_attr:name }}"{% endif %}
    />
</div>

blender_fund_main/templates/blender_fund_main/components/survey_field_opinion.html
<div class="radio-horizontal mt-3">
  {% with positive=positive|default:"Satisfied" negative=negative|default:"Dissatisfied" modifier=modifier|default:"Very" neutral=neutral|default:"Neutral" %}
    {% include f_radio with name=name id="very-negative" label=modifier|add:" "|add:negative %}
    {% include f_radio with name=name id="negative" label=negative %}
    {% include f_radio with name=name id="neutral" label=neutral %}
    {% include f_radio with name=name id="positive" label=positive %}
    {% include f_radio with name=name id="very-positive" label=modifier|add:" "|add:positive %}
  {% endwith %}
</div>

blender_fund_main/templates/blender_fund_main/components/survey_field_radio.html
{% load filters %}

<div
  class="js-toggle-element py-1"
  {% if is_other %}data-toggle-other="{{ name }}_{{ id }}__other_container"{% endif %}
  {% if toggle_section %}data-toggle-section="{{ toggle_section }}"{% endif %}
  {% if toggle_state %}data-toggle-state="{{ toggle_state|default:'on' }}"{% endif %}
  >
  <input
    type="{{ type|default:'radio' }}"
    value="{{ id }}"
    name="{{ name }}"
    id="{{ name }}_{{ id }}"
    {% if type == 'checkbox'%}
      {% if id in survey.response_data|get_attr:name %}checked{% endif %}
    {% else %}
      {% if survey.response_data|get_attr:name == id %}checked{% endif %}
    {% endif %}
  />

  <label {% if translate == "no" %}translate="no"{% endif %} for="{{ name }}_{{ id }}">{{ label }}</label>
</div>

{# Text field for "Other" option. Hidden by default. #}
{% if is_other %}
{% with name|add:'__other' as other_name_attr %}
<div
  id="{{ name }}_{{ id }}__other_container"
  class="form-group mb-0 {% if type == 'checkbox' and id in survey.response_data|get_attr:name %}is-visible{% elif type != 'checkbox' and survey.response_data|get_attr:name == id %}is-visible{% else %}is-hidden{% endif %}">

  <input
    class="form-control mt-2"
    type="text"
    id="{{ other_name_attr }}"
    name="{{ other_name_attr }}"
    maxlength="128"
    placeholder="Please specify..."
    {% if survey.response_data|get_attr:other_name_attr %}
      {% if type == 'checkbox'%}
        value="{{ survey.response_data|get_attr:other_name_attr|first }}"
      {% else %}
        value="{{ survey.response_data|get_attr:other_name_attr }}"
      {% endif %}
    {% endif %}>
</div>
{% endwith %}
{% endif %}

blender_fund_main/templates/blender_fund_main/components/survey_field_text.html
{% load filters %}

<div>
  {% if label %}
    <label for="{{ name }}_{{ id }}">{{ label }}</label>
  {% endif %}
  <input
    class="form-control {{ class }}"
    type="text"
    name="{{ name }}"
    id="{{ name }}_{{ id }}"
    {% if size %}size="{{ size}}"{% endif %}
    {% if minlength %}minlength="{{ minlength}}"{% endif %}
    {% if maxlength %}maxlength="{{ maxlength}}"{% endif %}
    {% if placeholder %}placeholder="{{ placeholder}}"{% endif %}
    {% if survey.response_data|get_attr:name %}value="{{ survey.response_data|get_attr:name }}"{% endif %}
    spellcheck=false
    />
</div>